version: '3'

services:
  go:
    image: "golang:latest"
    container_name: "golang-container"
    ports:
      - "8000:8000"
    depends_on:
      - "database"
    networks:
      - "localNetwork"
    volumes:
      - "./:/database"
    command: "tail -f > /dev/null"

  database:
    image: "mysql:latest"
    container_name: "mysql-container"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "test_db"
      MYSQL_ROOT_PASSWORD: "test_db"
    networks:
      - "localNetwork"

networks:
  localNetwork:
    driver: "bridge"  